# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "apps/web"
    schedule:
      interval: "weekly"
 - package-ecosystem: "npm" # See documentation for possible values
    directory: "libs/ui" # Location of package manifests
    schedule:
      interval: "weekly"
- package-ecosystem: "npm" # See documentation for possible values
    directory: "libs/shared" # Location of package manifests
    schedule:
      interval: "weekly"
- package-ecosystem: "uv" # See documentation for possible values
    directory: "libs/core" # Location of package manifests
    schedule:
      interval: "weekly"
- package-ecosystem: "uv" # See documentation for possible values
    directory: "libs/supabase-auth-provider" # Location of package manifests
    schedule:
      interval: "weekly"
- package-ecosystem: "uv" # See documentation for possible values
    directory: "apps/api" # Location of package manifests
    schedule:
      interval: "weekly"
- package-ecosystem: "uv" # See documentation for possible values
    directory: "tools/cli" # Location of package manifests
    schedule:
      interval: "weekly"
