# fly.toml app configuration file generated for api-cool-sun-8659 on 2025-08-07T22:59:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-cool-sun-8659'
primary_region = 'sjc'

[build]
  dockerfile = "apps/api/Dockerfile"
  context = "../.."

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
